// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJhUj9D49EmBReQ_9Hm3Tab9uDl7Ijpw',
    appId: '1:19280037862:web:10eea99d6f771d9d4d3827',
    messagingSenderId: '19280037862',
    projectId: 'facebook-17c8c',
    authDomain: 'facebook-17c8c.firebaseapp.com',
    databaseURL: 'https://facebook-17c8c-default-rtdb.firebaseio.com',
    storageBucket: 'facebook-17c8c.appspot.com',
    measurementId: 'G-LXS81Y87SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgh1ZwDNVd2VshR7DkDoDzpFovxdQQTE',
    appId: '1:19280037862:android:3c597aaab6b9b7ee4d3827',
    messagingSenderId: '19280037862',
    projectId: 'facebook-17c8c',
    databaseURL: 'https://facebook-17c8c-default-rtdb.firebaseio.com',
    storageBucket: 'facebook-17c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0J8zn2deTFNRy7Taa2-hre5df-qpXnWY',
    appId: '1:19280037862:ios:18f6e63ed396fd344d3827',
    messagingSenderId: '19280037862',
    projectId: 'facebook-17c8c',
    databaseURL: 'https://facebook-17c8c-default-rtdb.firebaseio.com',
    storageBucket: 'facebook-17c8c.appspot.com',
    iosBundleId: 'com.example.facebook',
  );

}